name: Release (testing)
on:
  push:
    # Matching on any tags which is not a production release
    # Matching:
    #  - v1.0.0-beta5
    #  - v1.0.1-rc3
    #  - v2.1.4-hotfix-87
    #
    # Ignoring:
    #  - v1.0.0
    #  - v1.1.0
    #  - v2.1.13
    tags:
      - 'v*-*'

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        make getdeps
        make
      env:
        GO111MODULE: on

    - name: Collecting files
      run: |
        scripts/collect.sh ${{ github.workspace }}/archive

    - name: Uploading flist (${{ github.ref }})
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-autobuilder
        root: archive
        name: tfexplorer-${{ github.ref }}.flist
    
    - name: Rename flist from tfexplorer-${{ github.ref }}.flist to tfexplorer:${{ github.ref }}.flist
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: rename
        user: tf-autobuilder
        name: tfexplorer-${{ github.ref }}.flist
        target: tfexplorer:${{ github.ref }}.flist

    - name: Symlink flist (development)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-autobuilder
        name: tfexplorer:development:latest.flist
        target: tf-autobuilder/tfexplorer:${{ github.ref }}.flist
    
    - name: Symlink flist (testing)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-official-apps
        name: tfexplorer:testing:latest.flist
        target: tf-autobuilder/tfexplorer:${{ github.ref }}.flist

